before_script:
  - apt-get update && apt-get install -y nodejs
  - node --version
  - npm --version
  - java -version # Required for selenium server
  - npm install
  - ./scripts/setup_ci.sh

test:
  script:
    - xvfb-run ./scripts/run_ci.sh

