stages:
  - test
  - cleanup

before_script:
  - echo "Starting tests..."

#test_linux:
#  script:
#    #- apt-get install -y nodejs nodejs-legacy npm default-jre
#    - node --version
#    - npm --version
#    - java -version # Required for selenium server
#    - npm install
#    - xvfb-run ./scripts/kill_applications.sh
#    - xvfb-run ./scripts/setup_linux.sh
#    - xvfb-run ./scripts/test.sh
#    - xvfb-run ./scripts/kill_applications.sh
#  tags:
#    - linux
#  allow_failure: true

test_windows:
  stage: test
  script:
    - git config --global http.sslVerify false
    - call scripts\kill_applications.bat
    - call npm install # https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1025
    - bash scripts/setup_windows.sh
    - call scripts\test.bat
  tags:
    - windows

cleanup:
  stage: cleanup
  when: always
  allow_failure: true
  script:
    - call npm install rimraf
    - call scripts\kill_applications.bat
    - call node_modules\.bin\rimraf testapp\XD-MVC
  tags:
    - windows
